### PR TITLE
Adding support for iPhone11,2 + iPhone11,4 + iPhone11,8

### PR DESCRIPTION
**Pull request by Coeur**
source: Xcode 10 GM simulators

### CODE REVIEW

**Comment by squarefrog** [comment]
Lightning fast work! Thank you 👍

**Comment by mflint** [comment]
Some websites report the Xs Max is also known as “iPhone 11,6”. Can anyone confirm this?
Source: https://www.theiphonewiki.com/wiki/List_of_iPhones

**Comment by squarefrog** [comment]
This was added in https://github.com/squarefrog/UIDeviceIdentifier/commit/dfd210488406ff3d50f66a583819973e6820be4d

I suspect the 11,6 is either the China variant or the non-international American model. Unable to confirm as I live in the UK.

**Comment by squarefrog** [comment]
My company has an office in Shenzhen I’ll see if any of the team has access to one.

**Pull request merged**
