### PR TITLE
example projects

### PR DESCRIPTION
**Pull request by Coeur**

### CODE REVIEW

**Comment by squarefrog** [comment]
I'm not sure we really need an example project. I think this could be achieved by updating the Readme to supply code for both Objective-C and Swift.

What do you think?

**Comment by Coeur** [comment]
I believe we need an example project to support test targets.

**Comment by squarefrog** [comment]
True, but I'm not sure how we'd go about testing this, as we can't mock the code in `+ (NSString *) platform`.

**Comment by Coeur** [comment]
Now, to be honest, I don't use UIDeviceIdentifier... I just have the [6 lines of `+platform` in swift](https://stackoverflow.com/a/25467259/1033581) and I'm sending the raw string to backend as-is, leaving the naming to them.

So if you don't need an example project, so be it, it's fine to close this PR. :)

**Comment by squarefrog** [comment]
Fair enough. I'll close this off. Thanks for taking the time to make this Pull Request though, I appreciate it.

**Pull request closed without merging**
